### ISSUE TITLE
probleme with run application 

### ISSUE THREAD

**Issue by alaeddineboukicha** [imsudip/instapost#1]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  C:\Users\ALADIN-PC\IdeaProjects\testapp\android\app\src\nullnull\google-services.json
  C:\Users\ALADIN-PC\IdeaProjects\testapp\android\app\src\debug\google-services.json
  C:\Users\ALADIN-PC\IdeaProjects\testapp\android\app\src\nullnullDebug\google-services.json
  C:\Users\ALADIN-PC\IdeaProjects\testapp\android\app\src\nullnull\debug\google-services.json
  C:\Users\ALADIN-PC\IdeaProjects\testapp\android\app\src\debug\nullnull\google-services.json
  C:\Users\ALADIN-PC\IdeaProjects\testapp\android\app\google-services.json

**Comment by imsudip** [comment]
add your own google-services.json from your firebase console
